name: ci and cd
on:
    push:
        branches: [ '**' ]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            - name: Install Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --editable .[dev]
            - name: Run black
              run: black --preview --check .
            - name: Run isort
              run: isort --check .

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            - name: Install Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --editable .[dev]
            - name: Run pylint
              run: pylint --fail-on all chessticulate_api

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            - name: Install Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --editable .[dev]
            - name: Run pytest
              run: pytest

    check-version:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v4
            - name: Install Python 3.11
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Check Version Increment
              run: scripts/check_version.sh

    push-to-registry:
        runs-on: ubuntu-latest
        needs: [format, lint, test, check-version]
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Get version number
              run: |
                VERSION=$(./scripts/get_version.sh)
                echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ secrets.GHCR_USERNAME }}
                password: ${{ secrets.GHCR_TOKEN }}

            - name: Build and push amd64 image
              uses: docker/build-push-action@v6
              with:
                push: true
                platforms: linux/amd64
                tags: |
                  ghcr.io/chessticulate/chessticulate-api-linux-amd64:v${{ env.VERSION }}
                  ghcr.io/chessticulate/chessticulate-api-linux-amd64:latest

            - name: Build and push arm64 image
              uses: docker/build-push-action@v6
              with:
                push: true
                platforms: linux/arm64/v8
                tags: |
                  ghcr.io/chessticulate/chessticulate-api-linux-arm64v8:v${{ env.VERSION }}
                  ghcr.io/chessticulate/chessticulate-api-linux-arm64v8:latest
