name: ci and cd
on:
    push:
        branches: [ '**' ]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --editable .[dev]
            - name: Run black
              run: black --preview --check .
            - name: Run isort
              run: isort --check .

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --editable .[dev]
            - name: Run pylint
              run: pylint --fail-on all chessticulate_api

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --editable .[dev]
            - name: Run pytest
              run: pytest

    check-version:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Check Version Increment
              run: scripts/check_version.sh

    push-to-registry:
        runs-on: ubuntu-latest
        needs: [format, lint, test, check-version]
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Get version number
              run: |
                VERSION=$(./get_version.sh)
                echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ secrets.GHCR_USERNAME }}
                password: ${{ secrets.GHCR_TOKEN }}

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ghcr.io/${{ github.repository }}:${{ env.VERSION }}

