name: ci
on:
    push:
        branches: [ '**' ]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --editable .[dev]
            - name: Run black
              run: black --preview --check .
            - name: Run isort
              run: isort --check .

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --editable .[dev]
            - name: Run pylint
              run: pylint --fail-on all chessticulate_api

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install --editable .[dev]
            - name: Run pytest
              run: pytest

    check-version:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v3
            - name: Install Python 3.10
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
            - name: Check Version Increment
              run: scripts/check_version.sh

